__version__: str

class UUID:
    def __init__(self, value: int | str | UUID) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: UUID) -> bool: ...
    def __le__(self, other: UUID) -> bool: ...
    def __gt__(self, other: UUID) -> bool: ...
    def __ge__(self, other: UUID) -> bool: ...

    @property
    def int(self) -> int: ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def hex(self) -> str: ...
    @property
    def urn(self) -> str: ...
    @property
    def time(self) -> int: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def version(self) -> int: ...
    @property
    def variant(self) -> str: ...
    @property
    def fields(self) -> tuple[int, int, int, int, int, int]: ...

def gen_id() -> int: ...
def gen_id_with_sub_ms_4() -> int: ...
def gen_id_with_sub_ms_8() -> int: ...
def gen_id_with_sub_ms_12() -> int: ...
def gen_id_str() -> str: ...
def gen_id_bytes() -> bytes: ...
def format_uuid(id: int | str | UUID) -> str: ...

def uuid7() -> UUID: ...
def uuid7_str() -> str: ...
def uuid7_hex() -> str: ...
def uuid7_bytes() -> bytes: ...
