__version__: str

def gen_id() -> int: ...
def gen_id_with_sub_ms_4() -> int: ...
def gen_id_with_sub_ms_8() -> int: ...
def gen_id_with_sub_ms_12() -> int: ...
def gen_id_str() -> str: ...
def gen_id_bytes() -> bytes: ...
def format_uuid(id: int) -> str: ...

def uuid7() -> str: ...
def uuid7_bytes() -> bytes: ...
