[package]
name = "fastuuidv7"
version.workspace = true
edition = "2024"
description = "Python bindings for fast-uuid-v7."
license.workspace = true

[lib]
name = "fastuuidv7"
crate-type = ["cdylib"]

[dependencies]
fast-uuid-v7 = { path = ".." }
pyo3 = { version = "0.28.3", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.28.3"
