[package]
name = "fastuuidv7"
version.workspace = true
edition = "2024"
description = "Python bindings for fast-uuid-v7."
license.workspace = true

[lib]
name = "fastuuidv7"
crate-type = ["cdylib"]

[features]
default = ["mimalloc"]
mimalloc = ["dep:mimalloc"]

[dependencies]
fast-uuid-v7 = { path = ".." }
mimalloc = { version = "0.1", default-features = false, optional = true }
pyo3 = { version = "0.29.0", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.29.0"
